/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TinTucImport } from './routes/tin-tuc'
import { Route as ThuVienImport } from './routes/thu-vien'
import { Route as ThongTinImport } from './routes/thong-tin'
import { Route as PasswordImport } from './routes/password'
import { Route as LoginImport } from './routes/login'
import { Route as LienHeImport } from './routes/lien-he'
import { Route as KhoaHocImport } from './routes/khoa-hoc'
import { Route as GioiThieuImport } from './routes/gioi-thieu'
import { Route as DichVuImport } from './routes/dich-vu'
import { Route as BannerImport } from './routes/banner'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TinTucRoute = TinTucImport.update({
  path: '/tin-tuc',
  getParentRoute: () => rootRoute,
} as any)

const ThuVienRoute = ThuVienImport.update({
  path: '/thu-vien',
  getParentRoute: () => rootRoute,
} as any)

const ThongTinRoute = ThongTinImport.update({
  path: '/thong-tin',
  getParentRoute: () => rootRoute,
} as any)

const PasswordRoute = PasswordImport.update({
  path: '/password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LienHeRoute = LienHeImport.update({
  path: '/lien-he',
  getParentRoute: () => rootRoute,
} as any)

const KhoaHocRoute = KhoaHocImport.update({
  path: '/khoa-hoc',
  getParentRoute: () => rootRoute,
} as any)

const GioiThieuRoute = GioiThieuImport.update({
  path: '/gioi-thieu',
  getParentRoute: () => rootRoute,
} as any)

const DichVuRoute = DichVuImport.update({
  path: '/dich-vu',
  getParentRoute: () => rootRoute,
} as any)

const BannerRoute = BannerImport.update({
  path: '/banner',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/banner': {
      id: '/banner'
      path: '/banner'
      fullPath: '/banner'
      preLoaderRoute: typeof BannerImport
      parentRoute: typeof rootRoute
    }
    '/dich-vu': {
      id: '/dich-vu'
      path: '/dich-vu'
      fullPath: '/dich-vu'
      preLoaderRoute: typeof DichVuImport
      parentRoute: typeof rootRoute
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuImport
      parentRoute: typeof rootRoute
    }
    '/khoa-hoc': {
      id: '/khoa-hoc'
      path: '/khoa-hoc'
      fullPath: '/khoa-hoc'
      preLoaderRoute: typeof KhoaHocImport
      parentRoute: typeof rootRoute
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordImport
      parentRoute: typeof rootRoute
    }
    '/thong-tin': {
      id: '/thong-tin'
      path: '/thong-tin'
      fullPath: '/thong-tin'
      preLoaderRoute: typeof ThongTinImport
      parentRoute: typeof rootRoute
    }
    '/thu-vien': {
      id: '/thu-vien'
      path: '/thu-vien'
      fullPath: '/thu-vien'
      preLoaderRoute: typeof ThuVienImport
      parentRoute: typeof rootRoute
    }
    '/tin-tuc': {
      id: '/tin-tuc'
      path: '/tin-tuc'
      fullPath: '/tin-tuc'
      preLoaderRoute: typeof TinTucImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  BannerRoute,
  DichVuRoute,
  GioiThieuRoute,
  KhoaHocRoute,
  LienHeRoute,
  LoginRoute,
  PasswordRoute,
  ThongTinRoute,
  ThuVienRoute,
  TinTucRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/banner",
        "/dich-vu",
        "/gioi-thieu",
        "/khoa-hoc",
        "/lien-he",
        "/login",
        "/password",
        "/thong-tin",
        "/thu-vien",
        "/tin-tuc"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/banner": {
      "filePath": "banner.ts"
    },
    "/dich-vu": {
      "filePath": "dich-vu.ts"
    },
    "/gioi-thieu": {
      "filePath": "gioi-thieu.ts"
    },
    "/khoa-hoc": {
      "filePath": "khoa-hoc.ts"
    },
    "/lien-he": {
      "filePath": "lien-he.ts"
    },
    "/login": {
      "filePath": "login.ts"
    },
    "/password": {
      "filePath": "password.ts"
    },
    "/thong-tin": {
      "filePath": "thong-tin.ts"
    },
    "/thu-vien": {
      "filePath": "thu-vien.ts"
    },
    "/tin-tuc": {
      "filePath": "tin-tuc.ts"
    }
  }
}
ROUTE_MANIFEST_END */
